ansible_user: "davidg"
ansible_ssh_private_key_file: "/Users/davidg/.ssh/homelab"
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCljbqDRNpkfvYzvyjsgcKav6PgK9bcM1VHE8PF/mSj homelab-ansible-key"
