# Default values for devenv chart

replicaCount: 1

image:
  repository: homelab/devenv
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  ports:
    - name: nodejs
      port: 3000
      targetPort: 3000
    - name: python
      port: 5000
      targetPort: 5000
    - name: deno
      port: 8000
      targetPort: 8000
    - name: go
      port: 8080
      targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: devenv.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  # existingClaim: ""

# Environment variables
env:
  - name: WORKSPACE
    value: "/workspace"
  - name: TERM
    value: "xterm-256color"

# Additional volumes
extraVolumes: []
  # - name: ssh-keys
  #   secret:
  #     secretName: ssh-keys
  #     defaultMode: 0600

extraVolumeMounts: []
  # - name: ssh-keys
  #   mountPath: /home/developer/.ssh
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# Enable interactive terminal
stdin: true
tty: true